config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :tournaments do
    resources :teams, only: %i[show new create]
    resources :team_politics, only: %i[new create edit update destroy]
    member do
      post :join
      patch :launch
      patch :bids_validate
      get :ranking_details
    end
  end
  resources :matches do
    resources :line_ups, only: %i[show new create]
    resources :team_matches, only: %i[index] do
      member do
        get :match_score
      end
    end
    member do
      patch :update_results
    end
  end
  resources :users
  resources :line_ups, only: %i[destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Clash of Buzz - buzz to win © 2023 by Marine, Hervé, Gaël & Francis.
  </div>

</div>

app/views/shared/_navbar.html.erb
<header>
  <nav>
    <div class="container-pas-bootstrap">
      <div class="nav-logo">
        <%= link_to image_tag("logocoblanc.png"),root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav-links">
        <% if user_signed_in? %>
          <li><%= link_to "Mes tournois", user_path(current_user), class: "nav-link active" %></li>
          <li><%= link_to "Créer un Tournoi", new_tournament_path, class: "nav-link" %></li>
          <li><%= link_to "", "#", class: "nav-link" %></li>

          <li class="dropdown">
            <%= link_to image_tag(current_user.avatar, class: "avatar"), "#", class: "nav-link dropdown-toggle", role: "button", 'aria-haspopup': true, 'aria-expanded': false %>
            <ul class="dropdown-menu">
              <li><%= link_to "Règles du jeu", "#", class: "dropdown-item" %></li>
              <li><%= link_to "A propos", "#", class: "dropdown-item" %></li>
              <li><%= link_to "Se deconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
            </ul>
          </li>
          <li>
            <strong><%= current_user.nickname %></strong>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>

  </nav>
</header>