config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :tournaments do
    resources :teams, only: %i[show new create]
    resources :team_politics, only: %i[new create edit update destroy]
    member do
      post :join
      patch :launch
      patch :bids_validate
      get :ranking_details
    end
  end
  resources :matches do
    resources :line_ups, only: %i[show new create]
    resources :team_matches, only: %i[index] do
      member do
        get :match_score
      end
    end
    member do
      patch :update_results
    end
  end
  resources :users
  resources :line_ups, only: %i[destroy]
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :tournament
  has_many :line_ups, dependent: :destroy
  has_many :politics, through: :line_ups
  has_many :user_matches
  has_many :users, through: :user_matches
  has_many :team_matches, dependent: :destroy
  has_many :teams, through: :team_matches

  def my_team_match(user)
    # récupération des team_matches pour un match en particulier (match = self)
    team_matches = self.team_matches.pluck(:id)
    # récupération de mon team_match du match
    user.team_matches.find { |team_match| team_matches.include?(team_match.id) }
  end
end

app/controllers/matches_controller.rb
require "open-uri"
require "nokogiri"
require "date"

class MatchesController < ApplicationController
  def index
    @team = Team.where(tournament: params[:tournament_id], user: current_user).first
    @tournament = @team.tournament
    @matches = @team.matches.sort_by(&:date)
    @matches.each do |match|
      change_status(match)
    end
    @matches_composition = @matches.select{|match| match.statut == "Composition"}
    @matches_in_progress = @matches.select{|match| match.statut == "In progress"}
    @matches_closed = @matches.select{|match| match.statut == "Closed"}
  end

  def new
    @match = Match.new
    @teams = Team.all
  end

  def create
    @match = Match.new(match_params)
    @match = Team.find(params[:team_id])
    if @match.save
      redirect_to match_path(@match)
    else
      render :new
    end
  end

  def show
    @match = Match.find(params[:id])
    @tournament = @match.tournament
    @line_up = @match.line_ups
    # update_results
  end

  def update_results(match=nil)
    # @match = Match.find(params[:id])
    redirection_at_end = true unless match
    match = Match.find(params[:id]) unless match
    @line_up = match.line_ups
    @line_up.each do |line_up|
      result = 0
      page = 0
      correctif = 0

      # Tant que le score est un multiple de 10 on va à la page suivante (car il
      # y a 10 résultats par page, donc ça veut dire qu'on a marqué le max de points
      # pour les pages regardées et qu'il y a encore potentiellement d'autres pages
      # à aller chercher).
      while ((result + correctif) % 10).zero?
        page += 1
        fetch_data(line_up.politic.last_name, page)
        result += @score
        # le correctif correspond aux articles parus hier quand on est lundi. Le prendre
        # en compte dans la condition du while permet de s'arrêter au bon moment
        correctif += @sunday_yesterday
        # si score de cette page = 0 : on arrête d'itérer (pour éviter d'itérer
        # sans fin si on est bloqué sur un multiple de 10)
        break if @score.zero?
      end
      line_up.result = result
      line_up.save
    end
    match_score_count(match)
    redirect_to request.referrer if redirection_at_end
  end

  private

  MONTHS_ABBR_TO_NUM = {
    'janv.' => 1,
    'févr.' => 2,
    'mars' => 3,
    'avr.' => 4,
    'mai' => 5,
    'juin' => 6,
    'juil.' => 7,
    'août' => 8,
    'sept.' => 9,
    'oct.' => 10,
    'nov.' => 11,
    'déc.' => 12
  }

  def match_params
    params.require(:match).permit(:team_id)
  end

  def fetch_data(politic, i)
    @score = 0
    @sunday_yesterday = 0
    # on définit les 2 bornes entre lesquelles on compte les points
    today = Date.today
    last_monday = today - (today.wday - 1)
    # on va chercher les dates affichées sur la page n° i
    politic = CGI.escape(politic)
    @url = "https://www.dna.fr/recherche?q=#{politic}&x=1&y=5&x=1&y=1&page=#{i}"
    html_file = URI.open(@url).read
    @html_doc = Nokogiri::HTML.parse(html_file)
    @html_doc.search(".publish").each do |date_string|
      # on décompose la date pour vérifier sa validité
      date_string_with_num_month = date_string.text.strip.gsub(/#{MONTHS_ABBR_TO_NUM.keys.join('|')}/, MONTHS_ABBR_TO_NUM)
      date_components = date_string_with_num_month.split(' ')
      day = date_components[0].to_i
      month = date_components[1].to_i
      year = date_components[2].to_i
      # si la date est valide elle marque 1 point si elle comprise entre les 2 bornes
      if Date.valid_date?(year, month, day)
        date = Date.new(year, month, day)
        @score += 1 if date.between?(last_monday, today)
      # si la date n'est pas valide cela signifie qu'elle est de type "10h" ou "hier",
      # ça marque donc un point aussi (sauf si on est lundi et que la date est "Hier")
      elsif today.wday != 1 || !date_string.text.strip.include?("Hier")
        @score += 1
      elsif today.wday == 1 && date_string.text.strip.include?("Hier")
      # ce correctif (correspondant aux articles marqués "hier" quand on est lundi
      # aide la méthode update_results à savoir s'il faut continuer d'aller chercher
      # les pages suivantes
        @sunday_yesterday += 1
      end
    end
  end

  def match_score_count(match)
    @my_match_score = 0
    @match_score_adversary = 0
    # calcul du match_score par équipe
    line_ups = LineUp.where(match_id: match.id)
    match.teams.each do |team|
      if team.user == current_user
        line_ups.each do |line_up|
          @my_match_score += line_up.result if team.politics.include?(line_up.politic) && team.user == current_user
        end
      elsif team.user != current_user
        line_ups.each do |line_up|
          @match_score_adversary += line_up.result if team.politics.include?(line_up.politic) && team.user != current_user
        end
      end
      # Sauvegarde du match_score dans la db
      match.team_matches.each do |team_match|
        if team_match.team.user == current_user
          team_match.match_score = @my_match_score
        else
          team_match.match_score = @match_score_adversary
        end
        team_match.save
      end
      match.team_matches.sort.reverse
      match.winner = match.team_matches[0].team.name
      match.save
    end
  end

  def change_status(match)
    if Date.today > match.date && Date.today < (match.date + 7)
      match.statut = "In progress"
      match.save
    elsif Date.today > (match.date + 7) && match.statut != "Closed"
      match.statut = "Closed"
      update_results(match)
      match_score_count(match)
    end
  end
end

app/views/matches/_adversary_user_team.html.erb
<div class="adversary-container">
  <% @match.teams.each do |team| %>
    <% if team.user != current_user %>
      <h2 class="title-team-matches"><%= team.user.nickname %> club</h2>
      <div class="team-list">
        <ul>
          <% team.politics.each do |politic| %>
            <li class="team-list-politic-adv">
              <div class="politic-item-adv">
                <%= image_tag("avatars/#{politic.last_name.downcase.gsub("é", "e").gsub("è", "e").gsub("à", "a")}.png", class: "politic-avatar") %>
                <div class="politic-info">
                  <h2 class="politic-name"><%= politic.first_name %> <%= politic.last_name %></h2>
                  <p class="politic-board"><%= politic.politic_board %></p>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
</div>

app/views/matches/_current_user_team.html.erb
<% @match.teams.each do |team| %>
  <% if team.user == current_user %>
    <h2 class="title-team-matches">Ton club</h2>
    <div class="team-list">
      <% team.politics.each do |politic| %>
        <% unless @match.line_ups.exists?(politic_id: politic.id) %>
          <ul>
            <li class="team-list-politic">
              <div class="politic-item-current">
                <%= image_tag("avatars/#{politic.last_name.downcase.gsub("é", "e").gsub("è", "e").gsub("à", "a")}.png", class: "politic-avatar") %>
                <div class="politic-info">
                  <h2 class="politic-name"><%= politic.first_name %> <%= politic.last_name %></h2>
                  <p class="politic-board"><%= politic.politic_board %></p>
                </div>
              </div>
              <% if team.user == current_user && !@match.line_ups.exists?(politic_id: politic.id) %>
                <%= button_to "+", match_line_ups_path(@match, politic_id: politic.id), method: :post, class: "pixel_art_btn_match", id: "ton-club" %>
              <% end %>
            </li>
          </ul>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/matches/_match_selection.html.erb
<div>
  <% selection = [] %>
  <% @match.teams.each do |team| %>
    <% if team.user == current_user %>
      <% @match.line_ups.each do |line_up| %>
        <% selection << line_up %>
      <% end %>
    <% end %>
  <% end %>
  <h2 class="title-team-matches">Ta sélection</h2>
  <% @match.teams.each do |team| %>
    <% if team.user == current_user %>
      <% @match.line_ups.each do |line_up| %>
        <% if team.politics.include?(line_up.politic) && team.user == current_user %>
          <li class="team-list-politic-selection">
            <div class="politic-item-matches">
              <%= image_tag("avatars/#{line_up.politic.last_name.downcase.gsub("é", "e").gsub("è", "e").gsub("à", "a")}.png", class: "politic-avatar") %>
              <div class="politic-info">
                <h2 class="politic-name"><%= line_up.politic.first_name %> <%= line_up.politic.last_name %></h2>
                <p class="politic-board"><%= line_up.politic.politic_board %></p>
              </div>
            </div>
            <% if team.user == current_user && @match.line_ups.exists?(politic_id: line_up.politic.id) %>
              <%= form_with(url: line_up_path(line_up), method: :delete) do |f| %>
                <%= f.submit "-", class: "pixel_art_btn_match_black" %>
              <% end %>
            <% end %>
          </li>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/matches/index.html.erb
<div class="user-header">
  <h1 class="user-header-name">Mon calendrier</h1>
</div>
<div class="back">
  <%= link_to "retour", tournament_path(@tournament),class: "pixel_art_btn" %>
</div>
<div class="championship-results" id="container-matches">
<div class="margin">
  <%#  card for each match %>
      <% @matches_in_progress.each do |match| %>
      <div class="info">
    <p class='statut'>Match en cours</p>
    <p class='date_match'><%= match.date.strftime("%d/%m/%Y") %></p>
  </div>
        <div class="general_card">
            <div class="user_card_owner">
              <% match.team_matches.each do |team_match| %>
                <div class="partner_name">
                  <p><%= team_match.team.name if team_match.team.user == current_user %></p>
                </div>
              <% end %>
            </div>
            <div class="score_game_before">
              <% match.team_matches.each do |team_match| %>
                  <div class="partner_name">
                    <p><%= team_match.match_score if team_match.team.user == current_user %></p>
                  </div>
                  <% end %>
              <p><%=image_tag'sword2.png', class:'sword_online' %></p>
              <% match.team_matches.each do |team_match| %>
              <p><%= team_match.match_score if team_match.team.user != current_user %></p>
              <% end %>
            </div>
            <div class="user_card">
              <% match.team_matches.each do |team_match| %>
                <div class="partner_name">
                  <p><%= team_match.team.name if team_match.team.user != current_user %></p>
                </div>
                <p><%= team_match.team.user.nickname if team_match.team.user != current_user %></p>
              <% end %>
            </div>

          <%= button_to "Voir les resultats en direct", match_path(match), method: :get, class: "pixel_art_btn_tournament" %>
        </div>
      <% end %>
      <% @matches_composition.each do |match| %>
        <div class="info">
          <p class='statut'>Match a venir</p>
          <p class='date_match'><%= match.date.strftime("%d/%m/%Y") %></p>
        </div>
        <div class="general_card">
          <div class="user_card_owner">
            <% match.team_matches.each do |team_match| %>
              <p class='user_card_title'><%= team_match.team.name if team_match.team.user == current_user %></p>
            <% end %>
          </div>
          <div class="score_game_invisible">
              <% match.team_matches.each do |team_match| %>
                    <p><%= team_match.match_score if team_match.team.user == current_user %></p>
                  <% end %>
              <p><%=image_tag'sword2.png', class:'sword' %></p>
              <% match.team_matches.each do |team_match| %>
              <p><%= team_match.match_score if team_match.team.user != current_user %></p>
              <% end %>
            </div>
          <div class="user_card">
            <% match.team_matches.each do |team_match| %>
              <div class="partner_name">
              <p><%= team_match.team.name if team_match.team.user != current_user %></p>
              </div>
              <p><%= team_match.team.user.nickname if team_match.team.user != current_user %></p>
            <% end %>
          </div>
            <div class="button_pix">
            <%= button_to "Composez votre equipe", match_path(match), method: :get, class: "pixel_art_btn_tournament" %>
            </div>
        </div>
      <% end %>

      <% @matches_closed.each do |match| %>

      <div class="info">
        <p class='statut'>Match termine</p>
        <p class='date_match'><%= match.date.strftime("%d/%m/%Y") %></p>
      </div>

          <div class="general_card_off">
            <div class="user_card_owner_off">
              <% match.team_matches.each do |team_match| %>
              <div class="partner_name_black">
                <p><%= team_match.team.name if team_match.team.user == current_user %></p>
              </div>
              <% end %>
            </div>
            <div class="score_game">
              <% match.team_matches.each do |team_match| %>
                <div class="partner_name_black">
                  <p><%= team_match.match_score if team_match.team.user == current_user %></p>
                </div>

                  <% end %>
              <p><%=image_tag'sword2.png', class:'sword_reverse' %></p>
              <% match.team_matches.each do |team_match| %>
                <p><%= team_match.match_score if team_match.team.user != current_user %></p>
              <% end %>
            </div>
            <div class="user_card_owner_off">
              <div class="partner_name_black">
                <% match.team_matches.each do |team_match| %>
                      <p><%= team_match.team.name if team_match.team.user != current_user %></p>
                      <p><%= team_match.team.user.nickname if team_match.team.user != current_user %></p>
                <% end %>
              </div>
            </div>
              <%= button_to "Voir le detail des resultats", match_path(match), method: :get, class: "pixel_art_btn_tournament" %>

              </div>

        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/matches/show.html.erb
<div class="user-header">
  <h1 class="user-header-name">Match de la semaine</h1>
</div>
<div class="back">
  <%= link_to "retour", matches_path(tournament_id: @tournament),class: "pixel_art_btn" %>
</div>
<div class="container-match" id="container-match">
  <% if @match.statut == "In progress" %>
    <%= button_to "Mettre a jour les resultats", update_results_match_path(@match, match: @match), method: :patch, class: "pixel_art_btn_match_adversary refresh_button" %>
  <% end %>
  <div class="container-match-teams">
  <div class="container-match-vs">
    <% @match.teams.each_with_index do |team, index| %>
      <% if team.user == current_user %>
        <h2><%= team.name %></h2>
        <% if @match.statut == "Closed" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
    <span class="title-score">
      <% @match.team_matches.each do |team_match| %>
        <%= team_match.match_score if team_match.team.user == current_user && @match.statut != "Composition" %>
      <% end %>
    </span>
    <% if @match.statut == "In progress" %>
      <p><%=image_tag'sword2.png', class:'sword_online' %></p>
    <% else %>
      <p><%=image_tag'sword2.png', class:'sword' %></p>
    <% end %>
    <span class="title-score">
      <% @match.team_matches.each do |team_match| %>
        <%= team_match.match_score if team_match.team.user != current_user && @match.statut != "Composition" %>
      <% end %>
    </span>
    <div class="container-match-vs">
      <% @match.teams.each do |team| %>
        <% if team.user != current_user %>
          <h2><%= team.name %></h2>
        <% end %>
      <% end %>
    </div>
  </div>
  <br>
  <% if @match.statut == "Composition" %>
    <div class="container-match-composition">
      <div class="cut-container">
        <%= render "current_user_team" %>
      </div>
      <div class="match_selection" >
        <%= render "match_selection" %>
      </div>
      <div class="selection-divider">
        <%= render "adversary_user_team" %>
      </div>
    </div>
  <% end %>
  <% if @match.statut == "In progress" %>
    <div class="container-match-composition-progress">
      <div class="cut-container">
        <h3 class="title-team-matches">Ta sélection pour le match</h3>
        <% @match.teams.each do |team| %>
          <% if team.user == current_user %>
            <% @match.line_ups.each do |line_up| %>
              <% if team.politics.include?(line_up.politic) && team.user == current_user %>
                <ul>
                  <li class="team-list-politic-selection">
                    <div class="politic-item-matches">
                      <%= image_tag("avatars/#{line_up.politic.last_name.downcase.gsub("é", "e").gsub("è", "e").gsub("à", "a")}.png", class: "politic-avatar") %>
                      <div class="politic-info">
                        <h2 class="politic-name"><%= line_up.politic.first_name %> <%= line_up.politic.last_name %></h2>
                        <p class="politic-result"><%= line_up.result %> POINTS</p>
                      </div>
                    </div>
                  </li>
                </ul>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="cut-container">
        <h3 class="title-team-matches">Équipe adverse</h3>
        <% @match.teams.each do |team| %>
          <% if team.user != current_user %>
            <% @match.line_ups.each do |line_up| %>
              <% if team.politics.include?(line_up.politic) && team.user != current_user %>
                <ul>
                  <li class="team-list-politic-selection">
                    <div class="politic-item-matches">
                      <%= image_tag("avatars/#{line_up.politic.last_name.downcase.gsub("é", "e").gsub("è", "e").gsub("à", "a")}.png", class: "politic-avatar") %>
                      <div class="politic-info">
                        <h2 class="politic-name"><%= line_up.politic.first_name %> <%= line_up.politic.last_name %></h2>
                        <p class="politic-result"><%= line_up.result %> POINTS</p>
                      </div>
                    </div>
                  </li>
                </ul>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
    <% if @match.statut == "Closed" %>
    <div class="result-container">
      <div class="match-final-result">
        <h3 class="title-score">Match terminé</h3>
        <h4 class="winner-result">WINNER: <%= @match.winner %></h4>
      </div>
    </div>
    <div class="container-match-composition-progress">
      <div class="cut-container">
        <h3 class="title-team-matches">Les résultats de ton équipe</h3>
        <% @match.teams.each do |team| %>
          <% if team.user == current_user %>
            <% @match.line_ups.each do |line_up| %>
              <% if team.politics.include?(line_up.politic) && team.user == current_user %>
                <ul>
                  <li>
                    <div class="team-list-politic-selection d-flex">
                      <div class="politic-item-matches">
                        <%= image_tag("avatars/#{line_up.politic.last_name.downcase.gsub("é", "e").gsub("è", "e").gsub("à", "a")}.png", class: "politic-avatar") %>
                        <div class="politic-info">
                          <h2 class="politic-name"><%= line_up.politic.first_name %> <%= line_up.politic.last_name %></h2>
                          <p class="politic-board"><%= line_up.politic.politic_board %></p>
                          <p class="points"><%= line_up.result %> POINTS</p>
                        </div>
                      </div>
                    </div>
                  </li>
                </ul>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="cut-container">
        <h3 class="title-team-matches">Équipe adverse</h3>
        <% @match.teams.each do |team| %>
          <% if team.user != current_user %>
            <% @match.line_ups.each do |line_up| %>
              <% if team.politics.include?(line_up.politic) && team.user != current_user %>
                <ul>
                  <li>
                    <div class="team-list-politic-progress d-flex">
                      <div class="player-info">
                        <%= line_up.politic.first_name %> <%= line_up.politic.last_name %>
                        <%= image_tag("avatars/#{line_up.politic.last_name.downcase.gsub("é", "e").gsub("è", "e").gsub("à", "a")}.png", class: "team-list-avatar") %>
                        <p><%= line_up.result %> POINTS</p>
                      </div>
                    </div>
                  </li>
                </ul>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>